name: lotto
description: "로또를 재미있게 즐기는 방법"

publish_to: 'none' # pub.dev에 게시하려면 이 라인을 제거하십시오.

# 다음은 응용 프로그램의 버전과 빌드 번호를 정의합니다.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# 종속성은 패키지가 작동하기 위해 필요한 다른 패키지를 지정합니다.
# 패키지 종속성을 최신 버전으로 자동 업그레이드하려면
# 'flutter pub upgrade --major-versions'를 실행하는 것을 고려해 보십시오,
# 어떤 종속성이 더 최신인지 확인하려면 `flutter pub outdated`를 실행 하세요.

dependencies:
  flutter:
    sdk: flutter

  introduction_screen: ^3.1.2
  google_fonts: ^4.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  flutter_native_splash: ^2.2.18
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  provider: ^6.0.5
  kakaomap_webview: ^0.6.2
  webview_flutter: ^3.0.2
  geolocator: ^11.0.0  
  flame: ^1.16.0
  flutter_animate : ^4.5.0
  get: ^4.6.5

  intl: ^0.19.0
  google_sign_in: ^6.1.4
  http: ^0.13.5

# 다음은 응용프로그램에 Cupertino Icons 글꼴을 추가합니다.
# iOS 스타일 아이콘은 CupertinoIcons 클래스와 함께 사용합니다.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 아래의 "flutter_lints" 패키지에는 다음과 같은 권장 사항이 포함되어 있습니다
  # 패키지가 제공하는 세트는 루트에 있는 'analysis_options.yaml' 파일에서 활성화 됩니다 

  flutter_lints: ^3.0.2

flutter:

  # 다음 줄은 material 아이콘 글꼴이 응용프로그램에 포함되어 있는지 확인합니다,

  uses-material-design: true

# 응용프로그램에 asset을 추가하려면 다음과 같이 자산 섹션을 추가합니다:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # 응용프로그램에 사용자 지정 글꼴을 추가하려면 여기에 글꼴 섹션을 추가하십시오,
  # 이 "flutter" 섹션에서. 이 목록의 각 항목에는 글꼴 패밀리 이름을 가진 "family" 키가 있어야 합니다.
  # 그리고 글꼴에 대한 asset 및 기타 설명자를 제공하는 목록이 있는 "font" 키. 예를 들어 다음과 같습니다.

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
